package com.example.auth

import android.content.Context
import android.util.Log
import androidx.credentials.ClearCredentialStateRequest
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialCustomException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.example.AppSettings
import com.example.UserAuthState
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.FirebaseException
import com.google.firebase.FirebaseNetworkException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseAuthException
import com.google.firebase.auth.FirebaseAuthInvalidCredentialsException
import com.google.firebase.auth.FirebaseAuthInvalidUserException
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.withContext
import java.util.concurrent.atomic.AtomicBoolean

sealed class AuthResult {
    data class Success(
        val email: String,
        val displayName: String?,
        val photoUrl: String?,
        val uid: String
    ) : AuthResult()

    data class Error(val message: String) : AuthResult()
    data object Cancelled : AuthResult()
}

/**
 * Modern Google Authentication helper using AndroidX Credential Manager API and Firebase Auth.
 *
 * Enforces strict verification:
 * Google Credential Manager -> Google ID Token -> GoogleAuthProvider -> FirebaseAuth.signInWithCredential()
 * Authentication is ONLY successful when Firebase verifies the token.
 */
object GoogleAuthManager {

    private const val TAG = "GoogleAuthManager"

    // Concurrency guard to prevent duplicate concurrent sign-in requests
    private val isSigningInProgress = AtomicBoolean(false)

    val userAuthState: StateFlow<UserAuthState>
        get() = AppSettings.userAuthState

    /**
     * Resolves the Web OAuth 2.0 Client ID for Google Sign-In.
     * Checks strings.xml resource (auto-generated by Google Services Gradle plugin from google-services.json)
     * or a manually specified resource.
     * Returns null if not configured to prevent using fake/placeholder IDs.
     */
    fun getServerClientId(context: Context): String? {
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        if (resId != 0) {
            val resClientId = context.getString(resId)
            if (resClientId.isNotBlank()) {
                return resClientId
            }
        }
        return null
    }

    /**
     * Launches the Google Credential Manager One-Tap / Bottom Sheet sign-in flow.
     * Strict flow:
     * 1. Retrieve Google ID token via Credential Manager
     * 2. Authenticate against Firebase Auth with GoogleAuthProvider
     * 3. Upon Firebase success, update application state with the verified FirebaseUser
     * 4. If Firebase fails, clear state and report error to UI
     */
    suspend fun signInWithGoogle(
        context: Context,
        serverClientId: String? = null,
        filterByAuthorizedAccounts: Boolean = false,
        onResult: (AuthResult) -> Unit
    ) {
        // Prevent duplicate sign-in calls while one is already running
        if (!isSigningInProgress.compareAndSet(false, true)) {
            Log.w(TAG, "Sign-in operation already in progress, ignoring duplicate trigger.")
            withContext(Dispatchers.Main) {
                onResult(AuthResult.Error("Sign-in is already in progress. Please wait."))
            }
            return
        }

        try {
            val resolvedClientId = serverClientId ?: getServerClientId(context)
            if (resolvedClientId.isNullOrBlank()) {
                val errorMsg = "Web Client ID is not configured. Please ensure google-services.json contains a Web OAuth Client (client_type 3) or define 'default_web_client_id' in strings.xml."
                Log.e(TAG, errorMsg)
                withContext(Dispatchers.Main) {
                    onResult(AuthResult.Error(errorMsg))
                }
                return
            }

            val credentialManager = CredentialManager.create(context)

            val googleIdOption = GetGoogleIdOption.Builder()
                .setFilterByAuthorizedAccounts(filterByAuthorizedAccounts)
                .setServerClientId(resolvedClientId)
                .setAutoSelectEnabled(false)
                .build()

            val request = GetCredentialRequest.Builder()
                .addCredentialOption(googleIdOption)
                .build()

            val response = credentialManager.getCredential(
                request = request,
                context = context
            )

            val credential = response.credential
            if (credential is CustomCredential &&
                credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
            ) {
                val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                val idToken = googleIdTokenCredential.idToken

                if (idToken.isBlank()) {
                    withContext(Dispatchers.Main) {
                        onResult(AuthResult.Error("Received empty Google ID token from Credential Manager."))
                    }
                    return
                }

                // Strictly authenticate with Firebase Auth. Token is passed directly and never saved locally.
                val firebaseUser = authenticateWithFirebase(idToken)

                // Update application authentication state using authoritative FirebaseUser
                withContext(Dispatchers.Main) {
                    AppSettings.updateUserAuthFromFirebase(context, firebaseUser)
                    onResult(
                        AuthResult.Success(
                            email = firebaseUser.email ?: googleIdTokenCredential.id,
                            displayName = firebaseUser.displayName ?: googleIdTokenCredential.displayName,
                            photoUrl = firebaseUser.photoUrl?.toString() ?: googleIdTokenCredential.profilePictureUri?.toString(),
                            uid = firebaseUser.uid
                        )
                    )
                }
            } else {
                val err = "Unsupported credential returned: ${credential::class.java.simpleName}"
                Log.w(TAG, err)
                withContext(Dispatchers.Main) {
                    onResult(AuthResult.Error(err))
                }
            }
        } catch (e: GetCredentialCancellationException) {
            Log.d(TAG, "Google Sign-In was cancelled by user.")
            withContext(Dispatchers.Main) {
                onResult(AuthResult.Cancelled)
            }
        } catch (e: NoCredentialException) {
            Log.w(TAG, "No Google accounts available on device: ${e.message}")
            withContext(Dispatchers.Main) {
                onResult(AuthResult.Error("No Google account found on device. Please add a Google account in Android Settings."))
            }
        } catch (e: GetCredentialCustomException) {
            Log.e(TAG, "Credential Manager custom error: ${e.message}", e)
            withContext(Dispatchers.Main) {
                onResult(AuthResult.Error(formatCredentialError(e)))
            }
        } catch (e: GetCredentialException) {
            Log.e(TAG, "Credential Manager error: ${e.message}", e)
            withContext(Dispatchers.Main) {
                onResult(AuthResult.Error(formatCredentialError(e)))
            }
        } catch (e: FirebaseAuthInvalidCredentialsException) {
            Log.e(TAG, "Firebase rejected Google credentials: ${e.message}", e)
            withContext(Dispatchers.Main) {
                AppSettings.signOut(context)
                onResult(AuthResult.Error("Firebase Authentication failed: Invalid or expired Google token."))
            }
        } catch (e: FirebaseAuthInvalidUserException) {
            Log.e(TAG, "Firebase user disabled or deleted: ${e.message}", e)
            withContext(Dispatchers.Main) {
                AppSettings.signOut(context)
                onResult(AuthResult.Error("Firebase Authentication failed: Account is disabled or deleted."))
            }
        } catch (e: FirebaseNetworkException) {
            Log.e(TAG, "Firebase network error: ${e.message}", e)
            withContext(Dispatchers.Main) {
                AppSettings.signOut(context)
                onResult(AuthResult.Error("Network error: Unable to reach Firebase Authentication. Please check your connection."))
            }
        } catch (e: FirebaseAuthException) {
            Log.e(TAG, "Firebase Auth error: ${e.message}", e)
            withContext(Dispatchers.Main) {
                AppSettings.signOut(context)
                onResult(AuthResult.Error("Firebase Authentication failed: ${e.localizedMessage ?: e.message}"))
            }
        } catch (e: FirebaseException) {
            Log.e(TAG, "Firebase error: ${e.message}", e)
            withContext(Dispatchers.Main) {
                AppSettings.signOut(context)
                onResult(AuthResult.Error("Firebase error: ${e.localizedMessage ?: e.message}"))
            }
        } catch (e: Exception) {
            Log.e(TAG, "Unexpected error during Google Sign-In: ${e.message}", e)
            withContext(Dispatchers.Main) {
                AppSettings.signOut(context)
                onResult(AuthResult.Error(e.localizedMessage ?: "An unexpected error occurred during sign-in."))
            }
        } finally {
            isSigningInProgress.set(false)
        }
    }

    /**
     * Bridges Google ID token directly to Firebase Authentication on Dispatchers.IO.
     * Does NOT catch or swallow exceptions, ensuring failures propagate to caller.
     */
    private suspend fun authenticateWithFirebase(idToken: String): FirebaseUser = withContext(Dispatchers.IO) {
        val firebaseAuth = FirebaseAuth.getInstance()
        val credential = GoogleAuthProvider.getCredential(idToken, null)
        val authResult = firebaseAuth.signInWithCredential(credential).await()
        authResult.user ?: throw FirebaseAuthException(
            "ERROR_NO_USER",
            "Firebase user is null after authentication verification."
        )
    }

    /**
     * Maps low-level Credential Manager errors to actionable descriptions.
     */
    private fun formatCredentialError(e: Exception): String {
        val msg = e.message ?: return "Google Sign-In failed"
        return when {
            msg.contains("16:", ignoreCase = true) || msg.contains("CANNOT_BIND_TO_SERVICE", ignoreCase = true) ->
                "Google Play Services is unavailable or outdated. Please update Google Play Services."
            msg.contains("10:", ignoreCase = true) || msg.contains("DEVELOPER_ERROR", ignoreCase = true) ->
                "Configuration error (Developer Error 10). Verify that your SHA-1 signing fingerprint and Web Client ID are registered in the Firebase Console."
            msg.contains("7:", ignoreCase = true) || msg.contains("NETWORK_ERROR", ignoreCase = true) ->
                "Network error. Please check your internet connection."
            msg.contains("12500", ignoreCase = true) ->
                "Google Sign-In configuration error (Status 12500). Please check Firebase Authentication settings."
            else -> msg
        }
    }

    /**
     * Signs out the user, clearing Credential Manager session, Firebase session, and local cache.
     */
    suspend fun signOut(context: Context) = withContext(Dispatchers.IO) {
        try {
            val credentialManager = CredentialManager.create(context)
            credentialManager.clearCredentialState(ClearCredentialStateRequest())
        } catch (e: Exception) {
            Log.w(TAG, "Failed clearing CredentialManager state: ${e.message}")
        }

        try {
            FirebaseAuth.getInstance().signOut()
        } catch (e: Exception) {
            Log.w(TAG, "Failed signing out of Firebase Auth: ${e.message}")
        }

        withContext(Dispatchers.Main) {
            AppSettings.signOut(context)
        }
    }
}
